CDHS Admin/CDHS_ADMIN/Models/AddHypertensionContentViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.ComponentModel.DataAnnotations;

namespace CDHS_ADMIN.Models
{
    public class AddHypertensionContentViewModel
    {
        [DataType(DataType.Text)]
        [Display(Name = "Priority")]
        public IEnumerable<PriorityListModel> PriorityList { get; set; }
        public string Priority { get; set; }

        [DataType(DataType.Text)]
        [Display(Name = "Approval")]
        public IEnumerable<ApprovalListModel> ApprovalList { get; set; }
        public string Approval { get; set; }

        [DataType(DataType.Text)]
        [Display(Name = "Asset")]
        public IEnumerable<AssetListModel> AssetList { get; set; }
        public string Asset { get; set; }

        //[DataType(DataType.Text)]
        //[Display(Name = "ContentTypeName")]
        public string ContentTypeName { get; set; }

        public string ContentCategoryName { get; set; }

        public string CompanyName { get; set; }
        public string id { get; set; }
        public string Title { get; set; }

        public string contentid { get; set; }
        public string categoryname { get; set; }
        public string categoryid { get; set; }
        public string companyname { get; set; }

        public string HyperTensionContaintDetails { get; set; }

        public string NewsDate { get; set; }

        public string SelectedPriority { get; set; }

        public string SelectedApprovalStatus { get; set; }

        public string SelectedAssetStatus { get; set; }

        public string AssetType { get; set; }

        public string UploadPhoto { get; set; }

        public string DragHeretoUpload { get; set; }
    }
}

CDHS Admin/CDHS_ADMIN/Models/AddHypertensionSymptomsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.ComponentModel.DataAnnotations;

namespace CDHS_ADMIN.Models
{
    public class AddHypertensionSymptomsViewModel
    {
        [DataType(DataType.Text)]
        [Display(Name = "Approval")]
        public IEnumerable<ApprovalListModel> ApprovalList { get; set; }
        public string Approval { get; set; }

        [DataType(DataType.Text)]
        [Display(Name = "Asset")]
        public IEnumerable<AssetListModel> AssetList { get; set; }
        public string Asset { get; set; }

        public string HyperTensionSymptomsTitle { get; set; }

        public string ContentBy { get; set; }
        public string id { get; set; }
        public string companyname { get; set; }



        public string ShortDescription { get; set; }

        public string HyperTensionSymptomsDetails { get; set; }

        public string SelectedApprovalStatus { get; set; }

        public string SelectedAssetStatus { get; set; }

        public string UploadTitleImage { get; set; }
    }
}

CDHS Admin/CDHS_ADMIN/Models/ViewHypertensionSymptomsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.ComponentModel.DataAnnotations;

namespace CDHS_ADMIN.Models
{
    public class ViewHypertensionSymptomsViewModel
    {
        [DataType(DataType.Text)]
        [Display(Name = "Approval")]
        public IEnumerable<ApprovalListModel> ApprovalList { get; set; }
        public string Approval { get; set; }

        [DataType(DataType.Text)]
        [Display(Name = "Asset")]
        public IEnumerable<AssetListModel> AssetList { get; set; }
        public string Asset { get; set; }

        public string SearchByContentType { get; set; }

        public string SearchByContentCategory { get; set; }

        public string SearchByContentSponsors { get; set; }

        public bool Loremipsumdolor { get; set; }

        public bool SelectedApprovalStatus { get; set; }

        public string SelectedAssetStatus { get; set; }





    }
}

CDHS Admin/CDHS_ADMIN/Controllers/HypertensionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CDHS_ADMIN.Models;

namespace CDHS_ADMIN.Controllers
{
    public class HypertensionController : Controller
    {
        private cdhsCommonMethods _cdhsCommonMethods = new cdhsCommonMethods();
        //
        // GET: /Hypertension/
        public ActionResult addhypertensioncontent()
        {
            AddHypertensionContentViewModel _AddHypertensionContentViewModel = new AddHypertensionContentViewModel();
            _AddHypertensionContentViewModel.PriorityList = new List<PriorityListModel>{
                new PriorityListModel{
                    id = "1", Priority = "Top"
                },
                new PriorityListModel{
                    id = "2", Priority = "Low"
                }
            };

            _AddHypertensionContentViewModel.ApprovalList = new List<ApprovalListModel>{
                new ApprovalListModel{
                    ApprovalId = "1", ApprovalStatus = "Awaiting For Approval"
                },
                new ApprovalListModel{
                    ApprovalId = "2", ApprovalStatus = "Approved"
                },
                new ApprovalListModel{
                    ApprovalId = "3", ApprovalStatus = "Reject"
                }
            };

            _AddHypertensionContentViewModel.AssetList = new List<AssetListModel>{
                new AssetListModel{
                    AssetId = "1", AssetStatus = "Image"
                },
                new AssetListModel{
                    AssetId = "2", AssetStatus = "Video"
                }
            };
            return View(_AddHypertensionContentViewModel);
        }
        public ActionResult addhypertensionsymptoms()
        {
            AddHypertensionSymptomsViewModel _AddHypertensionSymptomsViewModel = new AddHypertensionSymptomsViewModel();
            _AddHypertensionSymptomsViewModel.ApprovalList = new List<ApprovalListModel>{
                new ApprovalListModel{
                    ApprovalId = "1", ApprovalStatus = "Awaiting For Approval"
                },
                new ApprovalListModel{
                    ApprovalId = "2", ApprovalStatus = "Approved"
                },
                new ApprovalListModel{
                    ApprovalId = "3", ApprovalStatus = "Reject"
                }
            };

            _AddHypertensionSymptomsViewModel.AssetList = new List<AssetListModel>{
                new AssetListModel{
                    AssetId = "1", AssetStatus = "Image"
                },
                new AssetListModel{
                    AssetId = "2", AssetStatus = "Video"
                }
            };
            return View(_AddHypertensionSymptomsViewModel);
        }
        public ActionResult viewhypertensioncontent()
        {
            ViewHypertensionSymptomsViewModel _ViewHypertensionSymptomsViewModel = new ViewHypertensionSymptomsViewModel();
            _ViewHypertensionSymptomsViewModel.ApprovalList = new List<ApprovalListModel>{
                new ApprovalListModel{
                    ApprovalId = "1", ApprovalStatus = "Awaiting For Approval"
                },
                new ApprovalListModel{
                    ApprovalId = "2", ApprovalStatus = "Approved"
                },
                new ApprovalListModel{
                    ApprovalId = "3", ApprovalStatus = "Reject"
                }
            };

            _ViewHypertensionSymptomsViewModel.AssetList = new List<AssetListModel>{
                new AssetListModel{
                    AssetId = "1", AssetStatus = "Action"
                },
                new AssetListModel{
                    AssetId = "2", AssetStatus = "View"
                },
                                new AssetListModel{
                    AssetId = "3", AssetStatus = "Edit"
                },
                                new AssetListModel{
                    AssetId = "4", AssetStatus = "Delete"
                }
            };
            return View(_ViewHypertensionSymptomsViewModel);
        }
        public ActionResult viewhypertensionsymptoms()
        {
            return View();
        }

        #region Auto Complete Diabetes Content
        public ActionResult AutocompleteDiabetesContent(string searchstring)
        {
            JsonResult strSearch = _cdhsCommonMethods.ContentTypeGetSeacrchString(searchstring);
            return Json(strSearch, JsonRequestBehavior.AllowGet);
        }
        #endregion
        #region Auto Complete Diabetes Category
        public ActionResult AutocompleteDiabetesCategory(string searchstring)
        {
            JsonResult strSearch = _cdhsCommonMethods.ContentCategoryGetSeacrchString(searchstring);
            return Json(strSearch, JsonRequestBehavior.AllowGet);
        }
        #endregion
        #region Auto Complete Diabetes Company
        public ActionResult AutocompleteDiabetesCompany(string searchstring)
        {
            JsonResult strSearch = _cdhsCommonMethods.ContentCompanyGetSeacrchString(searchstring);
            return Json(strSearch, JsonRequestBehavior.AllowGet);
        }
        #endregion
	}
}

CDHS Admin/CDHS_ADMIN/Views/Hypertension/addhypertensioncontent.cshtml
@model CDHS_ADMIN.Models.AddHypertensionContentViewModel
@{
    ViewBag.Title = "addhypertensioncontent";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script src="@Url.Content("~/scripts/jquery-ui.min.js")" type="text/javascript"></script>
<script>
    $(function () {
        $("#content_type").autocomplete({
            source: function (request, response) {
                var eventtype = new Array();
                $.ajax({
                    method: "POST",
                    url: "/Hypertension/AutocompleteDiabetesContent",
                    data: "{searchstring:'" + $("#content_type").val() + "'}",
                    contentType: "application/json; charset=utf-8",
                    datatype: "json",
                    success: function (data) {
                        response($.map(data.Data, function (item) {
                            return {
                                label: item.label,
                                value: item.value
                            };
                        }));
                    },
                    error: function (XMLHttpRequest, textStatus, errorThrown) {
                        $("#content_type").text(textStatus);
                    }
                });

                //
                //response(eventtype);
            },
            minLength: 0,
            select: function (event, ui) {
                if (ui.item) {
                    $("#content_type").val(ui.item.label);
                    $("#contentid").val(ui.item.value);
                    return false;
                }
            },
            focus: function (event, ui) {
                return false;
            }
        }).focus(function () {
            $(this).data("autocomplete").search($(this).val());
            //$(this).trigger('mousedown.autocomplete');
        });
    });
</script>
<script>
    $(function () {
        $("#Category_Name").autocomplete({
            source: function (request, response) {
                var eventtype = new Array();
                $.ajax({
                    method: "POST",
                    url: "/Hypertension/AutocompleteDiabetesCategory",
                    data: "{searchstring:'" + $("#Category_Name").val() + "'}",
                    contentType: "application/json; charset=utf-8",
                    datatype: "json",
                    success: function (data) {
                        response($.map(data.Data, function (item) {
                            return {
                                label: item.label,
                                value: item.value
                            };
                        }));
                    },
                    error: function (XMLHttpRequest, textStatus, errorThrown) {
                        $("#Category_Name").text(textStatus);
                    }
                });

                //
                //response(eventtype);
            },
            minLength: 0,
            select: function (event, ui) {
                if (ui.item) {
                    $("#Category_Name").val(ui.item.label);
                    $("#categoryid").val(ui.item.value);
                    return false;
                }
            },
            focus: function (event, ui) {
                return false;
            }
        }).focus(function () {
            $(this).data("autocomplete").search($(this).val());
            //$(this).trigger('mousedown.autocomplete');
        });
    });
</script>
<script>
    $(function () {
        $("#companyname").autocomplete({
            source: function (request, response) {
                var eventtype = new Array();
                $.ajax({
                    method: "POST",
                    url: "/Hypertension/ContentCompanyGetSeacrchString",
                    data: "{searchstring:'" + $("#companyname").val() + "'}",
                    contentType: "application/json; charset=utf-8",
                    datatype: "json",
                    success: function (data) {
                        response($.map(data.Data, function (item) {
                            return {
                                label: item.label,
                                value: item.value
                            };
                        }));
                    },
                    error: function (XMLHttpRequest, textStatus, errorThrown) {
                        $("#companyname").text(textStatus);
                    }
                });

                //
                //response(eventtype);
            },
            minLength: 0,
            select: function (event, ui) {
                if (ui.item) {
                    $("#companyname").val(ui.item.label);
                    $("#sponsorid").val(ui.item.value);
                    return false;
                }
            },
            focus: function (event, ui) {
                return false;
            }
        }).focus(function () {
            $(this).data("autocomplete").search($(this).val());
            //$(this).trigger('mousedown.autocomplete');
        });
    });
</script>

<div class="content-block">
    <div class="container">
        <div class="breadcrumb">HEALTH TIPS > Hyper Tension Content</div>
    </div>
    <div class="container">
        <h2 class="title">
            Add Hyper Tension Content
            @Html.ActionLink("View Hyper Tension Content", "viewhypertensioncontent", "Hypertension", new { @class = "add-new" })
        </h2>
        <div class="hold-wrp">
@using (Html.BeginForm("addhypertensioncontent", "Hypertension", FormMethod.Post, new { @class = "form-horizontal", }))
{
            @*<form method="post" id="form_mast">*@
                <div class="form-wrap">
                    <div class="form-group clearfix">
                        <div class="col-lg-3">Content Type Name</div>
                        <div class="col-lg-9">@Html.TextBoxFor(m => m.ContentTypeName, new { @class = "form-control", @id = "content_type", @name = "content_type", @placeholder = "Search By Content Type" })
                            @Html.HiddenFor(m => m.contentid, new { @class = "form-control", @id = "contentid", @name = "contentid" })
                            @Html.HiddenFor(m => m.id, new { @class = "form-control", @id = "id", @name = "id" })</div>
                    </div>
                    <div class="form-group clearfix">
                        <div class="col-lg-3"> Content Category Name</div>
                        <div class="col-lg-9">
                        @*@Html.TextBoxFor(m => m.ContentCategoryName, new { @class = "form-control", @name = "content_cat", @placeholder = "Search By Content Category" })*@
                            @Html.TextBoxFor(m => m.categoryname, new { @class = "form-control", @id = "Category_Name", @name = "Category_Name", @placeholder = "Search By Content Category" })
                            @Html.HiddenFor(m => m.categoryid, new { @class = "form-control", @id = "categoryid", @name = "categoryid" })
                        </div>
                    </div>
                    <div class="form-group clearfix">
                        <div class="col-lg-3"> Company Name</div>
                        <div class="col-lg-9">
                            @Html.TextBoxFor(m => m.CompanyName, new { @class = "form-control", @id = "company_name", @name = "company_name", @placeholder = "Search By Sponsors Name" })
                            @Html.HiddenFor(m => m.companyname, new { @class = "form-control", @id = "companyname", @name = "companyname" })
                        </div>
                    </div>
                    <div class="form-group clearfix">
                        <div class="col-lg-3"> Title(Max 35 Charachters Allowed)</div>
                        <div class="col-lg-9">@Html.TextBoxFor(m => m.Title, new { @class = "form-control", @name = "title", @placeholder = "Enter Hyper Tension Content Title" })</div>
                    </div>
                    <div class="form-group clearfix">
                        <div class="col-lg-3">Hyper Tension Containt Details</div>
                        <div class="col-lg-9">@Html.TextAreaFor(m => m.HyperTensionContaintDetails, new { @class = "form-control", @style = "height:200px;" })</div>
                    </div>
                    <div class="form-group clearfix">
                        <div class="col-lg-3"> Date</div>
                        <div class="col-lg-9">
                            <div class='input-group date' id='datetimepicker5' data-date-format="DD/MM/YYYY">
                                @Html.TextBoxFor(m => m.NewsDate, new { @class = "form-control", @id = "newsDate", })
                                <span class="input-group-addon"><span class="glyphicon glyphicon-time"></span> </span>
                            </div>
                        </div>
                    </div>
                    <div class="form-group clearfix">
                        <div class="col-lg-3">Priority</div>
                        <div class="col-lg-9">
                            @Html.DropDownListFor(m => m.SelectedPriority, Model.PriorityList.Select(menu => new SelectListItem { Text = menu.Priority, Value = menu.id.ToString() }), new { @class = "form-control" })

                        </div>
                    </div>
                    <div class="form-group clearfix">
                        <div class="col-lg-3">Approval Status</div>
                        <div class="col-lg-9">
                            @Html.DropDownListFor(m => m.SelectedApprovalStatus, Model.ApprovalList.Select(menu => new SelectListItem { Text = menu.ApprovalStatus, Value = menu.ApprovalId.ToString() }), new { @class = "form-control" })

                        </div>
                    </div>
                    <div class="form-group clearfix">
                        <div class="col-lg-3">Asset Type</div>
                        <div class="col-lg-9">
                            @Html.DropDownListFor(m => m.SelectedAssetStatus, Model.AssetList.Select(menu => new SelectListItem { Text = menu.AssetStatus, Value = menu.AssetId.ToString() }), new { @class = "form-control" })

                        </div>
                    </div>
                    <div class="form-group clearfix">
                        <div class="col-lg-3">Upload Photo <br> (Size 500px X 500px)</div>
                        <div class="col-lg-9">
                            <div class="main_page_area">
                                <div class="" id="container">
                                    <div id="dropzone1" class="drag_area">Drag Here to Upload</div>
                                    <div id="actions">
                                        <div style="text-align:center"> <span style="display:none" class="btn btn-default fileinput-button"> <i class="glyphicon glyphicon-plus"></i> <span>Add files...</span> </span> </div>
                                        <div style="width:100%;">
                                            <span class="fileupload-process">
                                                <div id="total-progress" style="width:100%; margin-top:4px" class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0">
                                                    <div class="progress-bar progress-bar-success" style="width:0%;" data-dz-uploadprogress> </div>
                                                </div>
                                            </span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div>
                        <div class="form-group clearfix">
                            <div class="col-lg-3">&nbsp;</div>
                            <div class="col-lg-9">
                                <div class="sub_but">
                                    <input value="Submit" class="btn btn-primary" type="submit">
                                    <input value="Cancel" class="btn btn-primary" type="submit">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            @*</form>*@
}
        </div>
    </div>
</div>

CDHS Admin/CDHS_ADMIN/Views/Hypertension/addhypertensionsymptoms.cshtml
@model CDHS_ADMIN.Models.AddHypertensionSymptomsViewModel
@{
    ViewBag.Title = "addhypertensionsymptoms";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script src="@Url.Content("~/scripts/jquery-ui.min.js")" type="text/javascript"></script>
<script>
    $(function () {
        $("#companyname").autocomplete({
            source: function (request, response) {
                var eventtype = new Array();
                $.ajax({
                    method: "POST",
                    url: "/Hypertension/ContentCompanyGetSeacrchString",
                    data: "{searchstring:'" + $("#companyname").val() + "'}",
                    contentType: "application/json; charset=utf-8",
                    datatype: "json",
                    success: function (data) {
                        response($.map(data.Data, function (item) {
                            return {
                                label: item.label,
                                value: item.value
                            };
                        }));
                    },
                    error: function (XMLHttpRequest, textStatus, errorThrown) {
                        $("#companyname").text(textStatus);
                    }
                });

                //
                //response(eventtype);
            },
            minLength: 0,
            select: function (event, ui) {
                if (ui.item) {
                    $("#companyname").val(ui.item.label);
                    $("#sponsorid").val(ui.item.value);
                    return false;
                }
            },
            focus: function (event, ui) {
                return false;
            }
        }).focus(function () {
            $(this).data("autocomplete").search($(this).val());
            //$(this).trigger('mousedown.autocomplete');
        });
    });
</script>
<div class="content-block">
    <div class="container">
        <div class="breadcrumb">HEALTH TIPS >  Hyper Tension Symptoms</div>
    </div>
    <div class="container">
        <h2 class="title">
            Add  Hyper Tension Symptoms
            @Html.ActionLink("View  Hyper Tension Symptoms", "viewhypertensionsymptoms", "Hypertension", new { @class = "add-new" })
        </h2>
        <div class="hold-wrp">
@using (Html.BeginForm("addhypertensionsymptoms", "Hypertension", FormMethod.Post, new { @class = "form-horizontal", }))
{
            @*<form method="post" id="form_mast">*@
                <div class="form-wrap">
                    <div class="form-group clearfix">
                        <div class="col-lg-3">Hyper Tension Symptoms Title</div>
                        <div class="col-lg-9">@Html.TextBoxFor(m => m.HyperTensionSymptomsTitle, new { @class = "form-control", @name = "symptoms_title", @placeholder = "Enter Symptoms Title" }) 
                        @Html.HiddenFor(m => m.id, new { @class = "form-control", @id = "id", @name = "id" })</div>
                    </div>
                    <div class="form-group clearfix">
                        <div class="col-lg-3"> Content By</div>
                        <div class="col-lg-9">
                        @Html.TextBoxFor(m => m.ContentBy, new { @class = "form-control", @id = "sponsor_name", @name = "sponsor_name", @placeholder = "Search Sponsor Name" })
                        @Html.HiddenFor(m => m.companyname, new { @class = "form-control", @id = "companyname", @name = "companyname" })
                        </div>
                    </div>
                    <div class="form-group clearfix">
                        <div class="col-lg-3"> Short Description</div>
                        <div class="col-lg-9">@Html.TextBoxFor(m => m.ShortDescription, new { @class = "form-control", @placeholder = "Description In Short" })</div>
                    </div>

                    <div class="form-group clearfix">
                        <div class="col-lg-3">Hyper Tension Symptoms Details</div>
                        <div class="col-lg-9">@Html.TextAreaFor(m => m.HyperTensionSymptomsDetails, new { @class = "form-control", @style = "height:200px;" })</div>
                    </div>

                    <div class="form-group clearfix">
                        <div class="col-lg-3">Approval Status</div>
                        <div class="col-lg-9">
                            @Html.DropDownListFor(m => m.SelectedApprovalStatus, Model.ApprovalList.Select(menu => new SelectListItem { Text = menu.ApprovalStatus, Value = menu.ApprovalId.ToString() }), new { @class = "form-control" })
     
                        </div>
                    </div>
                    <div class="form-group clearfix">
                        <div class="col-lg-3">Asset Type</div>
                        <div class="col-lg-9">
                            @Html.DropDownListFor(m => m.SelectedAssetStatus, Model.AssetList.Select(menu => new SelectListItem { Text = menu.AssetStatus, Value = menu.AssetId.ToString() }), new { @class = "form-control" })
         
                        </div>
                    </div>
                    <div class="form-group clearfix">
                        <div class="col-lg-3">Upload Title Image</div>
                        <div class="col-lg-9">
                            <div class="main_page_area">
                                <div class="" id="container">
                                    <div id="dropzone1" class="drag_area">Drag Here to Upload</div>
                                    <div id="actions">
                                        <div style="text-align:center"> <span style="display:none" class="btn btn-default fileinput-button"> <i class="glyphicon glyphicon-plus"></i> <span>Add files...</span> </span> </div>
                                        <div style="width:100%;">
                                            <span class="fileupload-process">
                                                <div id="total-progress" style="width:100%; margin-top:4px" class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0">
                                                    <div class="progress-bar progress-bar-success" style="width:0%;" data-dz-uploadprogress> </div>
                                                </div>
                                            </span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div>
                        <div class="form-group clearfix">
                            <div class="col-lg-3">&nbsp;</div>
                            <div class="col-lg-9">
                                <div class="sub_but">
                                    <input value="Submit" class="btn btn-primary" type="submit">
                                    <input value="Cancel" class="btn btn-primary" type="submit">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            @*</form>*@
}
        </div>
    </div>
</div>